In [10]:
import tensorflow as tf

## Tensors

### Creating tensors

In [11]:
string = tf.Variable("This is a string", tf.string)
i = tf.Variable(324, tf.int16)
f = tf.Variable(3.24, tf.float64)

### Rank/Degree of tensors
No. of dimensions

In [12]:
# The tensors above are of rank 0

# tensor of rank 1:
rank1 = tf.Variable(["Test", "ok", "Lim"], tf.string)
# tensor of rank 2:
rank2 = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

# print tensor ranks
print(tf.rank(rank1))
print(tf.rank(rank2))
# print tensor shapes
print(rank1.shape)
print(rank2.shape)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
(3,)
(2, 2)


.reshape method

In [13]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

# Since we have 6 elements in this tensor, we should be able to "reshape" data
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape into (2,3,1) shape
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells tensorflow to auto-fill, in this case, it's [3,2]
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor <br>

Apart from Variable, all are immutable

### Evaluating tensors

In [14]:
with tf.Session() as sess: #creates a session using the default graph
    tensor1.eval() # evaluates sensor

AttributeError: module 'tensorflow' has no attribute 'Session'